# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Calamares grubcfg configuration for AetherOS
---

overwrite: false

prefer_grub_d: false

keep_distributor: false

kernel_params: [ "quiet", "loglevel=3" ]

defaults:
    GRUB_TIMEOUT: 5
    GRUB_DEFAULT: 0
    GRUB_DISABLE_SUBMENU: true
    GRUB_DISTRIBUTOR: "AetherOS"
    GRUB_CMDLINE_LINUX_DEFAULT: "quiet loglevel=3"

always_use_defaults: false
