---
units:
  - name: "NetworkManager.service"
    action: "enable"
    mandatory: true

  - name: "sddm.service"
    action: "enable"
    mandatory: true

  - name: "bluetooth.service"
    action: "enable"
    mandatory: false

  - name: "vmtoolsd.service"
    action: "enable"
    mandatory: false

  - name: "vboxservice.service"
    action: "enable"
    mandatory: false

  - name: "spice-vdagentd.service"
    action: "enable"
    mandatory: false

  - name: "live-setup.service"
    action: "mask"
    mandatory: false
