# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Calamares shellprocess module to run mkinitcpio on the target system
---

dontChroot: false

timeout: 300

script:
    - "mkinitcpio -P"

i18n:
    name: "Generating initial ramdisk (mkinitcpio)..."
