---
dontChroot: false
timeout: 30
script:
    - "-rm -f /etc/mkinitcpio.conf.d/archiso.conf"
    - "-rm -f /etc/sudoers.d/00-liveuser"
    - "-rm -f /etc/sddm.conf.d/autologin.conf"
    - "-rm -f /home/*/{Desktop,}/calamares.desktop"
    - "-rm -f /etc/skel/Desktop/calamares.desktop"
