# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Calamares shellprocess module to run mkinitcpio on the target system
---

dontChroot: false

timeout: 300

script:
    - "mkinitcpio -P"
    - "sh -c 'if [ -f /boot/Image ] && [ ! -f /boot/vmlinuz-linux ]; then cp -f /boot/Image /boot/vmlinuz-linux; fi'"
    - "sh -c 'if [ -f /boot/initramfs-linux-aarch64.img ] && [ ! -f /boot/initramfs-linux.img ]; then cp -f /boot/initramfs-linux-aarch64.img /boot/initramfs-linux.img; fi'"

i18n:
    name: "Generating initial ramdisk (mkinitcpio)..."
