---
defaultGroups:
    - lp
    - video
    - network
    - storage
    - wheel
    - audio
    - optical
    - power

autologinGroup:  autologin
doAutologin:     false
sudoersGroup:    wheel
setRootPassword: true
doReusePassword: true
emptyRootPassword: false
